spring.application.name=dsa_web_restservice
# Run this final Web Service on port 8085
server.port=8085

# 1. Hive JDBC Connection to Spark SQL's Thrift Server
spring.datasource.url=jdbc:hive2://localhost:10000/default
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver

# 2. JPA & Hibernate Configurations for Hive
# Hive doesn't support traditional Primary Keys or Auto-DDL, so we turn off table generation
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Tell Hibernate to treat the connection generically since Hive isn't a standard SQL DB
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl