spring.application.name=dsa_sql_oracle
# Change port to 8082 (Postgres is 8081, Oracle is 8082)
server.port=8082

# Oracle Connection String
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=J4DI_USER
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true